name:                sudoku
version:             0.1.0.0
github:              "prsteele/Sudoku"
license:             BSD3
author:              "Patrick Steele"
maintainer:          "steele.pat@gmail.com"
copyright:           "2018 Patrick Steele"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
synopsis:            A Sudoku solver
# category:            Web

description:         Please see the README on GitHub at <https://github.com/prsteele/Sudoku#readme>

dependencies:
  - base >= 4.7 && < 5
  - containers >= 0.6.0.1 && < 0.7
  - lens >= 4.17 && < 4.18
  - data-ordlist >= 0.4.7.0 && < 0.5
  - megaparsec >= 7.0.4 && < 7.1
  - mtl >= 2.2.2 && < 2.3

library:
  source-dirs: src

executables:
  sudoku:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - sudoku

tests:
  Sudoku-test:
    main:                Driver.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - sudoku
      - tasty >= 1.2 && < 1.3
      - tasty-discover >= 4.2.1 && < 4.3
      - tasty-hunit >= 0.10.0.1 && < 0.11
      - tasty-quickcheck >= 0.10 && < 0.11
